### PR TITLE
Fixed navbar responsive issues

### PR DESCRIPTION
**Pull request by aishwarya-mali**
## Fixes Issue
#11 

## Changes proposed
- removed css class

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

image

### CODE REVIEW

**Comment by ManishBisht777** [comment]
On the preview, the navbar still needs some spacing (320 px)

image

**Review by ManishBisht777 — CHANGES_REQUESTED** [review]
left some comments

**Comment by aishwarya-mali** [comment]
image

**Review by ManishBisht777 — APPROVED** [review]
Thanks for the contribution @aishwarya-mali , Looks great

**Pull request merged**
