### PR TITLE
Updated the Content of Home Page

### PR DESCRIPTION
**Pull request by sujitmemane**

### CODE REVIEW

**Review by ManishBisht777 — CHANGES_REQUESTED** [review]
Build is failing on /component/tracks

can you check it once

**Comment by sujitmemane** [comment]
> Build is failing on /component/tracks
> 
> can you check it once

Can you please also state a error

**Comment by ManishBisht777** [comment]
image
This is the error, however always make sure to run the build locally before pushing

**Review by ManishBisht777 — APPROVED** [review]
LGTM

**Pull request merged**
