### PR TITLE
[Feat]:fix Dark mode #4

### PR DESCRIPTION
**Pull request by vatan999**

### CODE REVIEW

**Comment by ManishBisht777** [comment]
Looks good but it needed a bit of changes 

1) Change the font color as well to match the dark mode

ex- 
## This can be changed to From
image

## This 
image

and so on

2) Change the image background in dark mode 

## From This
image

## to this
image


# Same this with these sections as well

Batch page
image

**Review by ManishBisht777 — COMMENTED** [review]
left some comments

**Review by ManishBisht777 — CHANGES_REQUESTED** [review]
:)

**Comment by vatan999** [comment]
Okay, I will make those changes

**Review by ManishBisht777 — CHANGES_REQUESTED** [review]
It still needs some changes please refer to the images that I have sent in the messages above

**Comment by ManishBisht777** [comment]
Thanks for your Contribution @vatan999  I will be taking these changes into separate branches merge accordingly

**Pull request closed without merging**
